gen1_pokemon = [
    "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard",
    "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree",
    "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate",
    "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash",
    "Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂", "Nidorino", "Nidoking", "Clefairy", "Clefable",
    "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume",
    "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck",
    "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam",
    "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude",
    "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch’d", "Doduo",
    "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee",
    "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan",
    "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen",
    "Seaking", "Staryu", "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados",
    "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl",
    "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew"
]

pokemon_types = [
    ("Grass", "Poison"), ("Grass", "Poison"), ("Grass", "Poison"), ("Fire", None), ("Fire", None), ("Fire", "Flying"),
    ("Water", None), ("Water", None), ("Water", None), ("Bug", None), ("Bug", None), ("Bug", "Flying"),
    ("Bug", "Poison"), ("Bug", "Poison"), ("Bug", "Poison"), ("Normal", "Flying"), ("Normal", "Flying"), ("Normal", "Flying"),
    ("Normal", None), ("Normal", None), ("Normal", "Flying"), ("Normal", "Flying"), ("Poison", None), ("Poison", None),
    ("Electric", None), ("Electric", None), ("Ground", None), ("Ground", None), ("Poison", None), ("Poison", None),
    ("Poison", "Ground"), ("Poison", None), ("Poison", None), ("Poison", "Ground"), ("Fairy", None), ("Fairy", None),
    ("Fire", None), ("Fire", None), ("Normal", None), ("Normal", None), ("Poison", "Flying"), ("Poison", "Flying"),
    ("Grass", "Poison"), ("Grass", "Poison"), ("Grass", "Poison"), ("Bug", None), ("Bug", None), ("Bug", "Poison"),
    ("Bug", "Poison"), ("Ground", None), ("Ground", None), ("Normal", None), ("Normal", None), ("Water", None),
    ("Water", None), ("Fighting", None), ("Fighting", None), ("Fire", None), ("Fire", None), ("Water", None),
    ("Water", None), ("Water", "Fighting"), ("Psychic", None), ("Psychic", None), ("Psychic", None), ("Fighting", None),
    ("Fighting", None), ("Fighting", None), ("Grass", "Poison"), ("Grass", "Poison"), ("Grass", "Poison"),
    ("Water", "Poison"), ("Water", "Poison"), ("Rock", "Ground"), ("Rock", "Ground"), ("Rock", "Ground"),
    ("Fire", None), ("Fire", None), ("Water", "Psychic"), ("Water", "Psychic"), ("Electric", None), ("Electric", None),
    ("Normal", "Flying"), ("Normal", "Flying"), ("Water", None), ("Water", "Ice"), ("Poison", None), ("Poison", None),
    ("Water", None), ("Water", "Ice"), ("Ghost", "Poison"), ("Ghost", "Poison"), ("Ghost", "Poison"), ("Rock", None),
    ("Psychic", None), ("Psychic", None), ("Water", None), ("Water", None), ("Electric", None), ("Electric", None),
    ("Grass", "Psychic"), ("Grass", "Psychic"), ("Ground", None), ("Ground", None), ("Fighting", None),
    ("Fighting", None), ("Normal", None), ("Poison", None), ("Poison", None), ("Ground", "Rock"), ("Ground", "Rock"),
    ("Normal", None), ("Grass", None), ("Normal", None), ("Water", None), ("Water", None), ("Water", "Poison"),
    ("Water", "Poison"), ("Water", None), ("Water", None), ("Water", "Psychic"), ("Bug", "Flying"), ("Ice", "Psychic"),
    ("Electric", None), ("Fire", None), ("Bug", None), ("Normal", None), ("Water", None), ("Water", None),
    ("Normal", None), ("Water", "Flying"), ("Water", "Flying"), ("Water", "Ice"), ("Normal", None), ("Normal", None),
    ("Water", None), ("Water", None), ("Water", None), ("Rock", "Water"), ("Rock", "Water"), ("Rock", "Water"),
    ("Rock", "Water"), ("Rock", "Flying"), ("Normal", None), ("Ice", "Flying"), ("Electric", "Flying"),
    ("Fire", "Flying"), ("Dragon", None), ("Dragon", None), ("Dragon", "Flying"), ("Psychic", None)
]